const FIGURINES_DATA =  {
  santasmailbox: {
    id: 1,
    village: 'General Products',
    category: 'Accessories',
    title: "Santa's Mailbox",
    itemUrl: 'https://www.lemaxcollection.com/villages/general-products/accessories/santa-s-mailbox-64073',
    imageUrl: '../../assets/images/houses/01-santasmailbox.png',
    retired: false,
    sku: 64073,
    yearReleased: 2013,
    yearRetired: 0,
    routeName: 'santas-mailbox',
  },
  waterfountain: {
    id: 2,
    village: 'Caddington',
    category: 'Accessories',
    title: "Water fountain",
    itemUrl: 'https://www.lemaxcollection.com/villages/caddington/accessories/water-fountain-04231',
    imageUrl: '../../assets/images/houses/02-waterfountain.png',
    retired: false,
    sku: 64073,
    yearReleased: 2010,
    yearRetired: 0,
    routeName: 'water-fountain',
  },
  snacktime: {
    id: 3,
    village: 'General Products',
    category: 'Figurines',
    title: "Snack Time",
    itemUrl: 'https://www.lemaxcollection.com/villages/general-products/figurines/snack-time-72405',
    imageUrl: '../../assets/images/houses/03-snacktime.png',
    retired: false,
    sku: 72405,
    yearReleased: 2010,
    yearRetired: 0,
    routeName: 'snack-time',
  },
  christmasparty: {
    id: 4,
    village: 'General Products',
    category: 'Figurines',
    title: "Christmas Party",
    itemUrl: 'https://www.lemaxcollection.com/villages/general-products/figurines/christmas-party--set-of-2-62445',
    imageUrl: '../../assets/images/houses/04-christmasparty.png',
    retired: false,
    sku: 62445,
    yearReleased: 2016,
    yearRetired: 0,
    routeName: 'christmas-party',
  },
  mediumvillagedisplayplatform: {
    id: 5,
    village: 'General Products',
    category: 'Landscaping',
    title: "Medium Village Display Platform",
    itemUrl: 'https://www.lemaxcollection.com/villages/general-products/landscaping/medium-village-display-platform-81015',
    imageUrl: '../../assets/images/houses/05-christmasparty.png',
    retired: false,
    sku: 81015,
    yearReleased: 1998,
    yearRetired: 0,
    routeName: 'medium-village-display-platform',
  },
  gaslampssetoffour: {
    id: 6,
    village: 'Caddington',
    category: 'Accessories',
    title: "Gas Lamps Set of Four",
    itemUrl: 'https://www.lemaxcollection.com/villages/caddington/accessories/4-gas-lantern-street-lamp--set-of-4-64498',
    imageUrl: '../../assets/images/houses/06-gaslampssetoffour.png',
    retired: false,
    sku: 64498,
    yearReleased: 2006,
    yearRetired: 0,
    routeName: 'gas-lamps-set-of-four',
  },
  christmasonhorseback: {
    id: 7,
    village: 'Holiday & Seasonal',
    category: 'Table Accents',
    title: "Christmas on Horseback",
    itemUrl: 'https://www.lemaxcollection.com/retired/holidays-seasons/table-accents/christmas-on-horseback-53214',
    imageUrl: '../../assets/images/houses/07-christmasonhorseback.png',
    retired: true,
    sku: 53214,
    yearReleased: 2015,
    yearRetired: 2019,
    routeName: 'christmas-on-horseback',
  },
};  

export default FIGURINES_DATA;