const HOUSE_DATA =  {
schoolgingerbreadfest: {
    id: 1,
    village: 'Holidays & Seasons',
    category: 'Lighted Buildings',
    title: 'School Gingerbread Fest',
    itemUrl: 'https://www.lemaxcollection.com/retired/holidays-seasons/lighted-buildings/school-gingerbread-fest-55949',
    imageUrl: '../../assets/images/houses/01-schoolgingerbreadfest.png',
    retired: true,
    sku: 55949,
    yearReleased: 2015,
    yearRetired: 2019,
    routeName: 'school-gingerbread-fest'
  },
  tudorpostofficer:  {
    id: 2,
    village: 'Caddington',
    category: 'Lighted Buildings',
    title: 'Tudor Lane Post Office',
    itemUrl: 'https://www.lemaxcollection.com/villages/caddington/lighted-buildings/tudor-lane-post-office-35519',
    imageUrl: '../../assets/images/houses/02-tudorpostoffice.png',
    retired: false,
    sku: 35519,
    yearReleased: 2013,
    yearRetired: 0,
    routeName: 'tudor-lane-post-office',
  },
  espressoyourself: {
    id: 3,
    village: 'Caddington',
    category: 'Lighted Buildings',
    title: 'Espresso Yourself',
    itemUrl: 'https://www.lemaxcollection.com/villages/caddington/lighted-buildings/espresso-yourself-85362',
    imageUrl: '../../assets/images/houses/03-espressoyourself.png',
    retired: false,
    sku: 85362,
    yearReleased: 2013,
    yearRetired: 0,
    routeName: 'tudor-lane-post-office',
  },
  fablesbookstore: {
    id: 4,
    village: 'Caddington',
    category: 'Lighted Buildings',
    title: 'Fables Bookstore',
    itemUrl: 'https://www.lemaxcollection.com/villages/caddington/lighted-buildings/fables-bookstore-85366',
    imageUrl: '../../assets/images/houses/04-fablesbookstore.png',
    retired: false,
    sku: 55949,
    yearRetired: 0,
    yearReleased: 2018,
    routeName: 'fables-bookstore',
  },
  leosfamouspizzeria: {
    id: 5,
    village: 'Holidays & Seasons',
    category: 'Lighted Buildings',
    title: "Leo's Famous Pizzeria ",
    itemUrl: 'https://www.lemaxcollection.com/retired/holidays-seasons/lighted-buildings/leo-s-famous-pizzeria-65151',
    imageUrl: '../../assets/images/houses/05-leosfamouspizza.png',
    retired: true,
    sku: 65151,
    yearRetired: 2019,
    yearReleased: 2017,
    routeName: 'leos-famous-pizzeria',
  },
  treelinebarandlounge: {
    id: 6,
    village: 'Holidays & Seasons',
    category: 'Lighted Buildings',
    title: 'Tree Line Bar & Lounge',
    itemUrl: 'https://www.lemaxcollection.com/retired/holidays-seasons/lighted-buildings/treeline-bar---lounge-45712',
    imageUrl: '../../assets/images/houses/06-treelinebarandlounge.png',
    retired: true,
    sku: 45712,
    yearReleased: 2013,
    yearRetired: 2017,
    routeName: 'treeline-bar-and-lounge',
  },
  pearlsicecreamparlor: {
    id: 7,
    village: 'Caddington',
    title: "Pearl's Ice Cream Parlor",
    category: 'Lighted Buildings',
    itemUrl: 'https://www.lemaxcollection.com/retired/holidays-seasons/lighted-buildings/pearl-s-ice-cream-parlor-85658',
    imageUrl: '../../assets/images/houses/07-pearlsicecreamparlor.png',
    retired: true,
    sku: 85658,
    yearReleased: 2008,
    yearRetired: 2016,
    routeName: 'pearlsicecreamparlor',
  },
  snowflakebundtcakes: {
    id: 8,
    village: 'Caddington',
    category: 'Lighted Buildings',
    title: 'Snowflake Bundt Cakes',
    itemUrl: 'https://www.lemaxcollection.com/villages/caddington/lighted-buildings/snowflake-bundt-cakes-85365',
    imageUrl: '../../assets/images/houses/08-snowflakebuntcakes.png',
    retired: false,
    sku: 85365,
    yearReleased: 2018,
    yearRetired: 0,
    routeName: 'snowflake-bundt-cakes',
  },
}
export default HOUSE_DATA;